### ISSUE TITLE
Add new Jobfile field for application specific customization

### ISSUE THREAD

**Issue by akashdhruv** [Lab-Notebooks/Jobrunner#5]
This will involve creating a new module under **jobrunner/instruments** which will be activated when Jobfile contains the field instrument,

```yaml
instrument: flashx

job:
  setup:
    - setupScript.sh
  submit:
    - submitScript.sh
   input:
    - domain.toml
    - parameters.toml
   target: flashx
```

This field be used to do instrument specific pre-processing. For the example above **jobrunner/instruments** will contain methods to convert the toml inputs to **flash.par**
